language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

script:
  - npm install coveralls
  - jest --maxWorkers=2
  - npm test -- -u --coverage
  
after_success:
  - npm run coveralls
