language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

script:
  - npm install coveralls
  - npm test -- -u --coverage
  - jest --maxWorkers=2

after_success:
  - npm run coveralls
